services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "manager@123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  migrate:
    build:
      context: .
      target: build
    working_dir: /src
    command: ["dotnet", "ef", "database", "update"]
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DockerDemo;User Id=sa;Password=manager@123;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  web:
    build:
      context: .
      target: final
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DockerDemo;User Id=sa;Password=manager@123;TrustServerCertificate=True;
    depends_on:
      - migrate

volumes:
  sql_data:
